##################################################################################
# Cloudify Azure built in types and plugins definitions.
# Version: 0.0.3-SNAPSHOT
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: cloudify-azure-plugin


node_types:
  cloudify.azure.nodes.ResourceGroup:
    derived_from: cloudify.nodes.Root
    properties:
      resource_group_name:
        description: >
          Indicates the name of the resource group to create
        type: string
        default: ''
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.resource_group.create
        delete:
          implementation: azure.plugin.resource_group.delete

  cloudify.azure.nodes.AvailabilitySet:
    derived_from: cloudify.nodes.Root
    properties:
      availability_set_name:
        type: string
        default: ''
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.availability_set.create
        delete:
          implementation: azure.plugin.availability_set.delete

  cloudify.azure.nodes.StorageAccount:
    derived_from: cloudify.nodes.Root
    properties:
      storage_account_name:
        type: string
        default: ''
      account_type:
        description: >
          account_type possible [Standard_LRS, Standard_ZRS, Standard_GRS, Standard_RAGRS, Premium_LRS]
        type: string
        default: 'Standard_LRS'
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.storage.create
        delete:
          implementation: azure.plugin.storage.delete

  cloudify.azure.nodes.Network:
    derived_from: cloudify.nodes.Network
    properties:
      virtual_network_name:
        type: string
        default: ''
      virtual_network_address_prefix:
        type: string
        default: ''
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.network.create
        delete:
          implementation: azure.plugin.network.delete

  cloudify.azure.nodes.Subnet:
    derived_from: cloudify.nodes.Network
    properties:
      subnet_name:
        type: string
        default: ''
      subnet_address_prefix:
        type: string
        default: ''
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.subnet.create
        delete:
          implementation: azure.plugin.subnet.delete

  cloudify.azure.nodes.NetworkInterfaceCard:
    derived_from: cloudify.nodes.Root
    properties:
      network_interface_name:
        type: string
        default: ''
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.nic.create
        delete:
          implementation: azure.plugin.nic.delete

  cloudify.azure.nodes.PublicIP:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      public_ip_name:
        type: string
        default: ''
      public_ip_allocation_method:
        type: string
        default: 'Dynamic'
      azure_config:
        default: {}
      deletable:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.public_ip.create
        delete:
          implementation: azure.plugin.public_ip.delete

  cloudify.azure.nodes.Datadisks:
    derived_from: cloudify.nodes.Root
    properties:
      disks:
        default: {}
        description: >
          A list of disks to attache to the machine. The required inputs are
          'name', 'caching' (None, ReadOnly or ReadWrite), 'attach' (True or False),
          and size (in GB).
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.datadisks.create

  cloudify.azure.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      publisher_name:
        type: string
      offer:
        type: string
      sku:
        type: string
      version:
        type: string
      flavor_id:
        type: string
      compute_name:
        type: string
      compute_user:
        type: string
      compute_password:
        type: string
      public_key:
        type: string
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.instance.create
        start:
          implementation: azure.plugin.instance.start
        stop:
          implementation: azure.plugin.instance.stop
        delete:
          implementation: azure.plugin.instance.delete

  cloudify.azure.nodes.WindowsInstance:
    derived_from: cloudify.azure.nodes.Instance
    properties:
      windows_automatic_updates:
        type: boolean
        default: false
      public_key:
        type: string
        default: ''
    interfaces:
      cloudify.interfaces.worker_installer:
        install: windows_agent_installer.windows_agent_installer.tasks.install
        start: windows_agent_installer.windows_agent_installer.tasks.start
        stop: windows_agent_installer.windows_agent_installer.tasks.stop
        uninstall: windows_agent_installer.windows_agent_installer.tasks.uninstall
        restart: windows_agent_installer.windows_agent_installer.tasks.restart
      cloudify.interfaces.plugin_installer:
        install: windows_plugin_installer.windows_plugin_installer.tasks.install


relationships:
  cloudify.azure.relationships.storage_account_contained_in_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.availability_set_contained_in_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.network_contained_in_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.subnet_connected_to_network:
    derived_from: cloudify.relationships.connected_to

  cloudify.azure.relationships.nic_connected_to_subnet:
    derived_from: cloudify.relationships.connected_to

  cloudify.azure.relationships.nic_connected_to_public_ip:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: azure.plugin.nic.add_public_ip

  cloudify.azure.relationships.public_ip_contained_in_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.instance_contained_in_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.instance_contained_in_availability_set:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.instance_depends_on_storage_account:
    derived_from: cloudify.relationships.depends_on

  cloudify.azure.relationships.instance_connected_to_nic:
    derived_from: cloudify.relationships.connected_to

  cloudify.azure.relationships.disk_attach_to_instance:
    derived_from: cloudify.relationships.connected_to

  cloudify.azure.relationships.disk_contained_in_storage_account:
    derived_from: cloudify.relationships.contained_in
