##################################################################################
# Cloudify Azure built in types and plugins definitions.
# Version: 0.0.1-SNAPSHOT
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: cloudify-azure-plugin

node_types:
  cloudify.azure.nodes.ResourceGroup:
    derived_from: cloudify.nodes.Root
    properties:
      resource_group_name:
        description: >
          Indicates the name of the resource group to create
        type: string
        default: ''
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.resource_group.create
        delete:
          implementation: azure.plugin.resource_group.delete

  cloudify.azure.nodes.StorageAccount:
    derived_from: cloudify.nodes.Root
    properties:
      storage_account_name:
        type: string
        default: ''
      account_type:
        description: >
          account_type possible [Standard_LRS, Standard_ZRS, Standard_GRS, Standard_RAGRS, Premium_LRS]
        type: string
        default: 'Standard_LRS'
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.storage.create
        delete:
          implementation: azure.plugin.storage.delete

  cloudify.azure.nodes.Network:
    derived_from: cloudify.nodes.Network
    properties:
      virtual_network_name:
        type: string
        default: ''
      virtual_network_address_prefix:
        type: string
        default: ''
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.network.create
        delete:
          implementation: azure.plugin.network.delete

  cloudify.azure.nodes.Subnet:
    derived_from: cloudify.nodes.Network
    properties:
      #virtual_network_name:
      #  type: string
      #  default: ''
      subnet_name:
        type: string
        default: ''
      subnet_address_prefix:
        type: string
        default: ''
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: azure.plugin.subnet.create
        delete:
          implementation: azure.plugin.network.delete

  cloudify.azure.nodes.Datadisks:
    derived_from: cloudify.nodes.Network
    properties:
      compute_name:
        type: string
        default: ''
      storage_account_name:
        type: string
        default: ''
      disks:
        default: {}
        description: >
          A list of disks to attache to the machine. The required inputs are
          'name', 'caching' (None, ReadOnly or ReadWrite), 'attach' (True or False),
          and size (in GB).
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.datadisks.create


  cloudify.azure.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      publisher_name:
        type: string
      offer:
        type: string
      sku:
        type: string
      version:
        type: string
      flavor_id:
        type: string
      compute_name:
        type: string
      storage_account_name:
        type: string
      compute_user:
        type: string
      compute_password:
        type: string
      public_key:
        type: string
      virtual_network_name:
        type: string
      subnet_name:
        type: string
      azure_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.plugin.instance.create
        start:
          implementation: azure.plugin.instance.start
        stop:
          implementation: azure.plugin.instance.stop
        delete:
          implementation: azure.plugin.instance.delete

relationships:
  cloudify.azure.relationships.storage_account_connected_to_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.network_connected_to_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.subnet_connected_to_network:
    derived_from: cloudify.relationships.connected_to
    source_interfaces: 
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: azure.plugin.subnet.preconfigure_subnet_connected_to_network

  cloudify.azure.relationships.instance_connected_to_resource_group:
    derived_from: cloudify.relationships.contained_in

  cloudify.azure.relationships.instance_connected_to_storage_account:
    derived_from: cloudify.relationships.depends_on

  cloudify.azure.relationships.instance_connected_to_network:
    derived_from: cloudify.relationships.connected_to

  cloudify.azure.relationships.instance_connected_to_subnet:
    derived_from: cloudify.relationships.connected_to
  
  cloudify.azure.relationships.disk_attach_to_instance:
    derived_from: cloudify.relationships.connected_to
