##################################################################################
# Cloudify Azure built in types and plugins definitions.
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-plugin-template/archive/3.2.zip

node_types:
    cloudify.azure.nodes.Instance:
        derived_from: cloudify.nodes.Compute
        properties:
            name:
                description: The name of the machine
                type: string
            image_id:
                description: >
                    The ID of the image to use on Azure.
                type: string
            instance_type:
                description: >
                    The instance's size.
                type: string
            cloud_service:
                description: The cloud service where the machine should be deployed.
                type: string
            storage_account_url:
                description: > 
                    The URL of the storage account where the OS hard disk of 
                    the machine should be stored.
        interfaces:
              cloudify.interfaces.lifecycle:
                create:
                  implementation: azure.instance.run_instances
                start:
                  implementation: azure.instance.start
                stop:
                  implementation: azure.instance.stop
                delete:
                  implementation: azure.instance.terminate
        cloudify.interfaces.validation:
            creation:
                implementation: azure.instance.creation_validation