##################################################################################
# Cloudify Azure built in types and plugins definitions.
# Version: 0.0.1-SNAPSHOT
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: .\cloudify-azure-plugin.zip

node_types:
    cloudify.azure.nodes.Instance:
        derived_from: cloudify.nodes.Compute
        properties:
            subscription_id:
                type: string
            username:
                type: string
            password:
                type: string
            location:   
                type: string
            publisherName:
                type: string
            offer:
                type: string
            sku:
                type: string
            version:
                type: string
            flavor_id:
                type: string
            compute_name:
                type: string
            network_interface_name:
                type: string
            storage_account:
                type: string
            compute_user:
                type: string
            compute_password:
                type: string
            public_key:
                type: string
            resource_group_name:
                type: string
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: azure.plugin.instance.create
                delete:
                    implementation: azure.plugin.instance.delete
